### ISSUE TITLE
Why use MDJWF?

### ISSUE THREAD

**Issue by DanJonesOcean** [so-wise/so-wise-gyre#32]
Question for @knaughten (no rush!):

I noticed that in your `mitgcm_python` code, you suggest using MDJWF in the mitgcm_python docs. Is that preferable to JMD95Z? I'm less familiar with MDJWF, and I can't find too much documentation on it.

**Comment by knaughten** [comment]
To be honest this is a case of inheriting a configuration from someone else (in this case Ruth Mugford, but other configurations inherited from Paul Holland and others all use MDJWF) and never bothering to change it or look into it very much! If you're using a different equation of state, just be sure it handles cold temperatures ok, and gets along with the shelfice package's expectations for in-situ versus potential temp.

**Comment by DanJonesOcean** [comment]
Thanks, @knaughten! Closing now
