### ISSUE TITLE
Need to control seaice package OBCS output 

### ISSUE THREAD

**Issue by DanJonesOcean** [so-wise/so-wise-gyre#36]
At present, we have lots and lots of `seaice_ob_` output that I'm not sure we need. This is causing the model to run very slowly. I need to investigate what controls this

**Comment by DanJonesOcean** [comment]
This also seems to be the case for `obcs_` in general. They seem to be outputting every timestep

**Comment by DaniJonesOcean** [comment]
I think I found it. The default is `OBCS_monitorFreq=monitorFreq`. Maybe if we just change this? Or maybe it's fine to keep it, just knowing that we'll get a *lot* of output if we ask for every timestep. 

This is fine. I get it now

**Comment by DaniJonesOcean** [comment]
Not really though, right? `monitor` is usually about summary statistics, not entire fields...

**Comment by DaniJonesOcean** [comment]
Yup, just did a test. It's a form of monitoring in OBCS. So that's how you control it
